### PR TITLE
phasespace generation

### PR DESCRIPTION
**Pull request by grzanka**

### CODE REVIEW

**Review by nbassler — CHANGES_REQUESTED** [review]
I think it would be better to 
move `data/sh12a/phasespace` to `data/sh12a/input/plan1_phasespace`
we would also need this for plan2 and plan 3 eventually.

**Comment by nbassler** [comment]
maybe also provide links to calculated mcpl files in `results/` ?
Should also include info how to acknowledge plgrid correctly.

**Comment by grzanka** [comment]
> I think it would be better to move `data/sh12a/phasespace` to `data/sh12a/input/plan1_phasespace` we would also need this for plan2 and plan 3 eventually.

That would create a lot of copy-pasted files. All the plans are there in a single directory, see

image

I create the jobs using following script which is reusing `geo.dat` and `mat.dat` for all plans:

https://github.com/APTG/2022_DCPT_LET/pull/44/files#diff-e42696e4247a95b85935affc5e1624e25525ef428b987ba5b91730e5d46cbbaf

```
PARTICLES=1000000
JOBS=100
WALLTIME=00:59:00

generatemc -p ${PARTICLES} -j ${JOBS} . -x beam_plan1.dat detect_plan1.dat plan1.dat -e ["--beamfile=beam_plan1.dat --detectfile=detect_plan1.dat"] -s ["-p plgrid --time ${WALLTIME}"] -w workspace1
generatemc -p ${PARTICLES} -j ${JOBS} . -x beam_plan2.dat detect_plan2.dat plan2.dat -e ["--beamfile=beam_plan2.dat --detectfile=detect_plan2.dat"] -s ["-p plgrid --time ${WALLTIME}"] -w workspace2
generatemc -p ${PARTICLES} -j ${JOBS} . -x beam_plan3.dat detect_plan3.dat plan3.dat -e ["--beamfile=beam_plan3.dat --detectfile=detect_plan3.dat"] -s ["-p plgrid --time ${WALLTIME}"] -w workspace3
```

**Comment by grzanka** [comment]
> maybe also provide links to calculated mcpl files in `results/` ? Should also include info how to acknowledge plgrid correctly.

Good idea, there is an issue for that https://github.com/APTG/2022_DCPT_LET/issues/45

**Comment by nbassler** [comment]
> > I think it would be better to move `data/sh12a/phasespace` to `data/sh12a/input/plan1_phasespace` we would also need this for plan2 and plan 3 eventually.
> 
> That would create a lot of copy-pasted files. All the plans are there in a single directory, see
> 

This only works, because phasespace files generated here are not geometry specifc, and that you run it on the cluster with generate mc. 
If a user would try to run all three in the same workdir from a simple computer, it will probably break, so we have two different approaches now, making the structure is less consistent now...
Alternatively one could also make a common folder for those files, and then point to those from the various runtime dirs. This way we avoid dublicate beam.dat, geo.dat and plan_sobp etc. Each could contain a readme.md with paths to all files needed.

Only issue is that SH cannot point to path for fetching stopping power files. Maybe this should be added.

**Review by nbassler — APPROVED** [review]

**Comment by nbassler** [comment]
approving for now, we can still refine structure later.

**Comment by nbassler** [comment]
> ```
> PARTICLES=1000000
> JOBS=100
> WALLTIME=00:59:00
> 
> generatemc -p ${PARTICLES} -j ${JOBS} . -x beam_plan1.dat detect_plan1.dat plan1.dat -e ["--beamfile=beam_plan1.dat --detectfile=detect_plan1.dat"] -s ["-p plgrid --time ${WALLTIME}"] -w workspace1
> generatemc -p ${PARTICLES} -j ${JOBS} . -x beam_plan2.dat detect_plan2.dat plan2.dat -e ["--beamfile=beam_plan2.dat --detectfile=detect_plan2.dat"] -s ["-p plgrid --time ${WALLTIME}"] -w workspace2
> generatemc -p ${PARTICLES} -j ${JOBS} . -x beam_plan3.dat detect_plan3.dat plan3.dat -e ["--beamfile=beam_plan3.dat --detectfile=detect_plan3.dat"] -s ["-p plgrid --time ${WALLTIME}"] -w workspace3
> ```

suggest, this could also go into a readme.md file in the phsp input directory.

**Pull request merged**
